language: go
sudo: false
go:
  - "1.13"
env:
  - GO111MODULE=on
script:
  - make test
  - make build
before_install:
  - openssl aes-256-cbc -K $encrypted_3c9c22204e1d_key -iv $encrypted_3c9c22204e1d_iv
    -in google-credentials.json.enc -out pkg/conf/google-credentials.json -d
