language: go
go:
  - "1.13"
env:
  - GO111MODULE=on
cache:
  directories:
    - $HOME/.cache/go-build # Cache the binaries
    - $HOME/gopath/pkg/mod # Cache the Go modules
script:
  - make test
  - make build
before_install:
  - openssl aes-256-cbc -K $encrypted_3c9c22204e1d_key -iv $encrypted_3c9c22204e1d_iv
    -in google-credentials.json.enc -out pkg/conf/google-credentials.json -d
