version: "3.8"
services:
  backend_db:
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=notifier
      - POSTGRES_USER=tino
      - POSTGRES_PASSWORD
      - POSTGRES_ROOT_PASSWORD
    volumes:
      - backend_postgresql:/var/lib/postgresql
      - backend_postgresql_data:/var/lib/postgresql/data
      - ./setupDB.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: .
    command: ["make"]
    env_file:
      - .env
    depends_on:
      - backend_db
    ports:
      - "8080:${PORT}"
    volumes:
      - backend_go_mod_data:/go/pkg/mod
volumes:
  backend_postgresql:
  backend_postgresql_data:
  backend_go_mod_data:
