openapi: "3.0.3"
info:
  version: "1.0"
  title: "Cominify API"
  description: API for Cominify chatbot
servers:
  - url: https://localhost:8080/api/v1
    description: Local Test Server
paths:
  /comics:
    get:
      # summary: "Get list of comics"
      description: "Return list of comics"
      operationId: Comics
      tags:
        - comic
      response:
        "200":
          description: Successfully return a list of comics
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Comic"
components:
  schemas:
    Comic:
      type: object
      properties:
        id:
          type: integer
          description: Comic ID
        page:
          type: string
          description: Page to read comic
        name:
          type: string
          description: Comic name
        url:
          type: string
          description: Comic url
        latest:
          type: string
          description: Comic's latest chapter
        chap-url:
          type: string
          description: Chapter url
