// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Comic struct {
	ID          int32
	Page        string
	Name        string
	Url         string
	ImgUrl      string
	CloudImgUrl string
	LatestChap  string
	ChapUrl     string
	LastUpdate  time.Time
}

type Subscriber struct {
	ID        int32
	UserID    int32
	ComicID   int32
	CreatedAt time.Time
}

type User struct {
	ID         int32
	Name       string
	Psid       sql.NullString
	Appid      sql.NullString
	ProfilePic sql.NullString
}
