// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Comic struct {
	ID          sql.NullInt32
	Page        string
	Name        string
	Url         string
	ImgUrl      string
	CloudImgUrl string
	LatestChap  string
	ChapUrl     string
}

type Subscriber struct {
	ID        sql.NullInt32
	UserPsid  sql.NullString
	ComicID   sql.NullInt32
	CreatedAt time.Time
}

type User struct {
	ID         sql.NullInt32
	Name       string
	Psid       string
	Appid      string
	ProfilePic string
}
