// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Comic struct {
	ID         sql.NullInt32
	Page       sql.NullString
	Name       sql.NullString
	Url        string
	ImgUrl     sql.NullString
	CloudImg   sql.NullString
	LatestChap string
	ChapUrl    string
}

type Subscriber struct {
	ID        sql.NullInt32
	UserPsid  sql.NullString
	ComicID   sql.NullInt32
	CreatedAt time.Time
}

type User struct {
	ID         sql.NullInt32
	Name       sql.NullString
	Psid       sql.NullString
	Appid      sql.NullString
	ProfilePic sql.NullString
}
